Vagrant.configure(2) do |config|
	config.vm.box      = "bento/ubuntu-16.04"
	config.vm.hostname = 'randoms.local'
	config.vm.network "private_network", ip: "192.168.56.20"

	# Change the VM allocated resources to the one specified below.
	# Also change the name of the VM in the VirtualBox interface.
	#
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
		vb.cpus = 2
		vb.name = "randoms"
		vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
	end

	# Sync the sources folder with the machine
	# !! Make sure you have the vagrant nfs plugin installed if running on Windows
	# vagrant plugin install vagrant-winnfsd
	config.vm.synced_folder "../", "/var/www/pw", type: "nfs"
end